docs : README.md에 컨벤션 관련사항 추가
woowacourse-moltudy/15-mins-retrospective pull request #28
Opened 2021-06-11 05:11 UTC by sihyung92

2021-06-11 05:49 UTC, pika96 reviewed
웨지?

2021-06-11 05:50 UTC, pika96 approved these changes
굿!! 좋네요 approve
진행하면서 추가하면 될 것 같아요~

2021-06-11 07:06 UTC, soulgchoi approved these changes

2021-06-11 07:40 UTC, da-nyee requested changes
안녕하세요, 웨지!

README 작성 수고하셨습니다 👍
코멘트 두 개 남겼는데 확인해주세요 ~!

2021-06-11 07:40 UTC, da-nyee commented on README.md
> +> feature/member-login, feature/fare-matching
```suggestion
> feature/member-login, feature/pair-matching
```

👀

2021-06-11 07:40 UTC, da-nyee commented on README.md
> +🚀 [레포지토리 링크](https://github.com/woowacourse-moltudy/15-mins-retrospective)
여기 레포에 나타나는 README인데, 레포지토리 링크를 작성할 필요가 있나요?

2021-06-11 23:46 UTC, sihyung92 commented on README.md
> +> feature/member-login, feature/fare-matching
ㅋㅋㅋ 수정하겟슴다

2021-06-11 23:49 UTC, sihyung92 commented on README.md
> +🚀 [레포지토리 링크](https://github.com/woowacourse-moltudy/15-mins-retrospective)
저는 IDE에서 볼 때가 많아서 넣어놨었는데 사실 전 url로 직접 들오는 경우가 많아서 필요없긴해요 ㅎ_ㅎ 지우겠습니당

2021-06-12 02:32 UTC, da-nyee approved these changes

2021-06-13 01:30 UTC, merged